baseURL: https://g396.github.io/diary/
languageCode: ja-jp
title: Razl-Dazl
theme: ezhil
timeZone: Asia/Tokyo

copyright: Razl-Dazl - g396.github.io

summaryLength: 999999

paginate: 7

pygmentsstyle: solarized-dark
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

menu:
  main:
    - name: about
      url: ../
      weight: 1
    - name: blog
      url: ../posts/
      weight: 10
    - name: diary
      url: ../diary/
      weight: 15

params:
  #for eyecatch img
  credit:
    android: Copyright © Google
    hugo: © 2014 Steve Francia
    obsidian: © 2022 Obsidian
  favicon: /favicon.png
  
permalinks:
  posts: /:section/:year/:month/:filename

taxonomies:
    tag: tags
    all-posts: all

publishDir: ../diary
